# == OUTPUT

# === ASCII ===
/gate/output/ascii/disable

# === ROOT output ===
/gate/output/root/enable
/gate/output/root/setFileName output/PhantomToF/{crystal}/output{rootfile}
/gate/output/root/setRootNtupleFlag 0
/gate/output/root/setRootHitFlag 0
/gate/output/root/setSaveRndmFlag 0
/gate/output/root/setRootRecordFlag 0
/gate/output/root/setRootSinglesFlag 0
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setRootDelayFlag 0
/gate/output/root/setRootSingles300Flag 0
/gate/output/root/setRootCoincidencesnoEWFlag 0
/gate/output/root/setRootDelaynoEWFlag 0

# == ACTOR
/gate/actor/addActor   SimulationStatisticActor stat
/gate/actor/stat/save  output/PhantomToF/{crystal}/stat{rootfile}.txt
/gate/actor/stat/saveEveryNEvents 2000

# Summary
/gate/output/summary/enable
/gate/output/summary/setFileName output/PhantomToF/{crystal}/summary{rootfile}.txt
/gate/output/summary/addCollection Singles
/gate/output/summary/addCollection Coincidences
/gate/output/summary/addCollection Delay

# Attenuation map
#/gate/actor/addActor MuMapActor getMuMap
#/gate/actor/getMuMap/attachTo world
#/gate/actor/getMuMap/save output/PhantomToF/{crystal}/MuMap{rootfile}.hdr
#/gate/actor/getMuMap/setPosition 0 0 0 mm
#/gate/actor/getMuMap/setVoxelSize 0.5 0.5 0.5 mm
#/gate/actor/getMuMap/setResolution 360 360 360
#/gate/actor/getMuMap/setEnergy 511 keV
#/gate/actor/getMuMap/setMuUnit 1  1/cm

