# == OUTPUT

# === ASCII ===
/gate/output/ascii/disable

# === ROOT output ===
/gate/output/root/enable
/gate/output/root/setFileName output/NECR/{crystal}/{activity}/output
/gate/output/root/setRootNtupleFlag 0
/gate/output/root/setRootHitFlag 0
/gate/output/root/setSaveRndmFlag 0
/gate/output/root/setRootRecordFlag 0
/gate/output/root/setRootSinglesFlag 0
/gate/output/root/setRootCoincidencesFlag 0
/gate/output/root/setRootDelayFlag 0
/gate/output/root/setRootSingles300Flag 0
/gate/output/root/setRootCoincidences300Flag 1
/gate/output/root/setRootDelay300Flag 1

# === new ROOT output ===
#/gate/output/tree/enable
#/gate/output/tree/addFileName output/NECR/{crystal}/{activity}/Data_AxialPos.npy
#/gate/output/tree/addFileName output/NECR/{crystal}/{activity}/Data_AxialPos.root
#/gate/output/tree/hits/enable
#/gate/output/tree/addCollection Singles
#/gate/output/tree/addCollection Coincidences
#/gate/output/tree/addCollection Delay
#/gate/output/tree/addCollection Singles300
#/gate/output/tree/addCollection Coincidences300
#/gate/output/tree/addCollection Delay300

# == ACTOR
/gate/actor/addActor   SimulationStatisticActor stat
/gate/actor/stat/save  output/NECR/{crystal}/{activity}/stat.txt
/gate/actor/stat/saveEveryNEvents 2000

# Summary
/gate/output/summary/enable
/gate/output/summary/setFileName output/NECR/{crystal}/{activity}/summary.txt
/gate/output/summary/addCollection Singles
/gate/output/summary/addCollection Coincidences
/gate/output/summary/addCollection Delay

# Attenuation map
#/gate/actor/addActor MuMapActor getMuMap
#/gate/actor/getMuMap/attachTo world
#/gate/actor/getMuMap/save output/MuMap.hdr
#/gate/actor/getMuMap/setPosition 0 0 0 mm
#/gate/actor/getMuMap/setVoxelSize 0.5 0.5 0.5 mm
#/gate/actor/getMuMap/setResolution 362 434 362
#/gate/actor/getMuMap/setEnergy 511 keV
#/gate/actor/getMuMap/setMuUnit 1  1/cm

