# == OUTPUT

# === ASCII ===
/gate/output/ascii/disable

# === ROOT output ===
/gate/output/root/enable
/gate/output/root/setFileName output/NEMABrain/{crystal}/output{rootfile}
/gate/output/root/setRootNtupleFlag 0
/gate/output/root/setRootHitFlag 0
/gate/output/root/setSaveRndmFlag 0
/gate/output/root/setRootRecordFlag 0
/gate/output/root/setRootSinglesFlag 0
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setRootDelayFlag 0
/gate/output/root/setRootSingles300Flag 0
/gate/output/root/setRootCoincidencesnoEWFlag 0
/gate/output/root/setRootDelaynoEWFlag 0

# == ACTOR
/gate/actor/addActor   SimulationStatisticActor stat
/gate/actor/stat/save  output/NEMABrain/{crystal}/stat{rootfile}.txt
/gate/actor/stat/saveEveryNEvents 2000

# Summary
/gate/output/summary/enable
/gate/output/summary/setFileName output/NEMABrain/{crystal}/summary{rootfile}.txt
/gate/output/summary/addCollection Singles
/gate/output/summary/addCollection Coincidences
/gate/output/summary/addCollection Delay

# Attenuation map
/gate/actor/addActor MuMapActor getMuMap
/gate/actor/getMuMap/attachTo world
/gate/actor/getMuMap/save output/NEMABrain/{crystal}/MuMap{rootfile}.hdr
/gate/actor/getMuMap/setPosition 0 0 0 mm
/gate/actor/getMuMap/setVoxelSize 1. 1. 1. mm
/gate/actor/getMuMap/setResolution 200 200 200
/gate/actor/getMuMap/setEnergy 511 keV
/gate/actor/getMuMap/setMuUnit 1  1/cm

